# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1108, 599)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(410, 10, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_plain = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_plain.setGeometry(QtCore.QRect(80, 100, 421, 131))
        self.txt_plain.setObjectName("txt_plain")
        self.txt_cipher = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_cipher.setGeometry(QtCore.QRect(80, 300, 421, 131))
        self.txt_cipher.setObjectName("txt_cipher")
        self.txt_information = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_information.setGeometry(QtCore.QRect(590, 100, 421, 131))
        self.txt_information.setObjectName("txt_information")
        self.txt_signature = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_signature.setGeometry(QtCore.QRect(590, 300, 421, 131))
        self.txt_signature.setObjectName("txt_signature")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(510, 100, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(520, 300, 61, 21))
        self.label_5.setObjectName("label_5")
        self.btn_generate = QtWidgets.QPushButton(Dialog)
        self.btn_generate.setGeometry(QtCore.QRect(670, 30, 101, 31))
        self.btn_generate.setObjectName("btn_generate")
        self.bnt_encrypt = QtWidgets.QPushButton(Dialog)
        self.bnt_encrypt.setGeometry(QtCore.QRect(130, 470, 93, 28))
        self.bnt_encrypt.setObjectName("bnt_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(Dialog)
        self.btn_decrypt.setGeometry(QtCore.QRect(340, 470, 93, 28))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(Dialog)
        self.btn_sign.setGeometry(QtCore.QRect(640, 470, 93, 28))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(Dialog)
        self.btn_verify.setGeometry(QtCore.QRect(900, 470, 93, 28))
        self.btn_verify.setObjectName("btn_verify")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "RSA CIPHER"))
        self.label_2.setText(_translate("Dialog", "Plain text:"))
        self.label_3.setText(_translate("Dialog", "Cipher text:"))
        self.label_4.setText(_translate("Dialog", "Information:"))
        self.label_5.setText(_translate("Dialog", "Signature"))
        self.btn_generate.setText(_translate("Dialog", "Generate Keys"))
        self.bnt_encrypt.setText(_translate("Dialog", "Encrypt"))
        self.btn_decrypt.setText(_translate("Dialog", "Decrypt"))
        self.btn_sign.setText(_translate("Dialog", "Sign"))
        self.btn_verify.setText(_translate("Dialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
